language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - DRIVER=mysqli SPHINXSEARCH_BUILD=rel21
  - DRIVER=mysqli SPHINXSEARCH_BUILD=rel22
  - DRIVER=pdo SPHINXSEARCH_BUILD=rel21
  - DRIVER=pdo SPHINXSEARCH_BUILD=rel22

matrix:
  allow_failures:
    - env: DRIVER=pdo SPHINXSEARCH_BUILD=rel21
    - env: DRIVER=pdo SPHINXSEARCH_BUILD=rel22

before_install:
  - sudo add-apt-repository ppa:builds/sphinxsearch-${SPHINXSEARCH_BUILD} -y
  - sudo apt-get update -q
  - sudo apt-get install sphinxsearch

before_script:
  - sudo service sphinxsearch stop
  - composer install --dev
  - cd tests
  - /usr/bin/searchd -c sphinx.conf

script: ../vendor/bin/phpunit --configuration travis/$DRIVER.phpunit.xml --coverage-text
