language: php

php:
  - 5.3
  - 5.4

notifications:
  email:
    - woxxy@foolrulez.org

before_install:
  - sudo apt-get install -qq libmysqlclient18
  - wget http://woxxy.foolz.us/sphinx-2.0.5-foolz.tar.gz
  - tar xvzf sphinx-2.0.5-foolz.tar.gz
  - cd sphinx-2.0.5-foolz
  - ./configure --prefix=/usr/local/sphinx
  - sudo make && sudo make install
  - cd ..

before_script:
  - cd tests
  - mkdir data
  - searchd -c sphinx.conf
  
script: phpunit --configuration phpunit.xml --coverage-text