language: php

php:
  - 5.3
  - 5.4
  
services:
  - mysql

notifications:
  email:
    - woxxy@foolrulez.org
  irc: "irc.irchighway.net#fooldriver"

before_install:
  - sudo apt-get install -qq libmysqlclient18
  - sudo apt-get install -qq sphinxsearch

before_script:
  - cd tests
  - mkdir data
  - searchd -c sphinx.conf
  
script: phpunit --configuration phpunit.xml --coverage-text